packages:
  - net-tools
  - vim
  - curl
  - unzip
  - tar
  - wget
  - firewalld
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-devel
  - python2
  - python2-devel
  - python3
  - python3-devel
  - chrony
  - openssl
  - openssl-devel

python_rpm_packages:
  - python2-backports
  - python2-backports-lzma
  - python2-six
  - python2-pycurl
  - python2-rpm
  - python2-rpmUtils
  - python2-urlgrabber
  - python2-yum
  - yum-metadata-parser

master_host: '127.0.0.1'

openjdk_package: java-1.8.0-openjdk-devel

ntp_service_name: chronyd

firewall_service_name: firewalld

