version: '3.3'

services:
  rocky1:
    build:
      context: rocky1/
    hostname: 'rocky1.big.data'
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    privileged: true
    networks:
      default_bridge:
        ipv4_address: 172.26.0.11
    command: /sbin/init
  rocky2:
    build:
      context: rocky2/
    hostname: 'rocky2.big.data'
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    privileged: true
    networks:
      default_bridge:
        ipv4_address: 172.26.0.12
    command: /sbin/init
  rocky3:
    build:
      context: rocky3/
    hostname: 'rocky3.big.data'
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    privileged: true
    networks:
      default_bridge:
        ipv4_address: 172.26.0.13
    command: /sbin/init

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/24