version: '3.3'

x-ambari-common:
  &ambari-common
  init: true
  stdin_open: true
  tty: true
  volumes:
    &ambari-common-volume
    - ./data:/data
  privileged: true
  command: /sbin/init

services:
  node1:
    <<: *ambari-common
    build:
      context: ./ubuntu22/
      dockerfile: Dockerfile.ambari-server
    hostname: 'node1.big.data'
    ports:
      - 8080:8080
    networks:
      default_bridge:
        ipv4_address: 172.26.0.11
  node2:
    <<: *ambari-common
    build:
      context: ./ubuntu22/
      dockerfile: Dockerfile.ambari-agent
    hostname: 'node2.big.data'
    networks:
      default_bridge:
        ipv4_address: 172.26.0.12
  node3:
    <<: *ambari-common
    build:
      context: ./ubuntu22/
      dockerfile: Dockerfile.ambari-agent
    hostname: 'node3.big.data'
    networks:
      default_bridge:
        ipv4_address: 172.26.0.13

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/24