FROM ubuntu:22.04

RUN apt -y update && apt upgrade && \
    apt -y install wget net-tools && \
    apt -y install python3 python3-dev && \
    apt -y install ansible

COPY ansible-playbook /root/ansible-playbook

RUN ansible-playbook -i /root/ansible-playbook/inventory.yml /root/ansible-playbook/ambari-server.yml > /root/ansible.log

CMD [ "/bin/bash" ]