FROM rockylinux:8.6

RUN ["/bin/bash", "dnf -y install epel-release"]
RUN ["/bin/bash", "dnf -y install ncurses wget net-tools"]
RUN ["/bin/bash", "dnf -y install python3 python3-devel"]
RUN ["/bin/bash", "dnf -y install ansible"]