# 시간 동기화 서비스 설치
- name: Install Time Sync Package
  dnf:
    name: chrony
    state: installed
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

# chrony 서비스 설정
# TODO: master 서버 정보 변경
# TODO: allow 대역 변경
- block:
    - name: Create chrony config file
      file:
        path: /etc/chrony.conf
        state: touch
    - name: chrony config in .conf file
      lineinfile:
        path: /etc/chrony.conf
        line: "{{ item.line }}"
      loop:
        - {line: 'server master01.big.data iburst'}
        - {line: ''}
        - {line: 'log tracking measurements statistics'}
        - {line: 'logchange 0.5'}
        - {line: ''}
        - {line: 'logdir /var/log/chrony'}
        - {line: ''}
        - {line: 'allow {{ chrony_allow }}'}

# chrony 재시작 및 부팅 시 자동 시작
- name: chrony restart, enable
  systemd_service:
    name: chronyd
    enabled: true
    state: restarted

# ambari agent 설치
- name: Install Ambari Agent
  dnf:
    name: ambari-agent
    state: installed
  when:
    - ansible_distribution|lower == "redhat"
    - ansible_distribution_major_version|int == "8"

