# chrony 서비스 설정
# TODO: master 서버 정보 변경
# TODO: allow 대역 변경
- block:
    - name: Create chrony config file
      file:
        path: /etc/chrony.conf
        state: touch
    - name: chrony config in .conf file
      lineinfile:
        path: /etc/chrony.conf
        line: "{{ item.line }}"
      loop:
        - {line: 'server master01.big.data iburst'}
        - {line: ''}
        - {line: 'log tracking measurements statistics'}
        - {line: 'logchange 0.5'}
        - {line: ''}
        - {line: 'logdir /var/log/chrony'}
        - {line: ''}
        - {line: 'allow {{ chrony_allow }}'}

# ambari agent 설치
- name: Install Ambari Agent
  package:
    name: ambari-agent
    state: installed

